Update client optimizer
APPFL/APPFL pull request #114
Opened 2023-04-04 16:00 UTC by minseok-ryu

1. Create more functions to cover more cost functions and algorithms supported by PyTorch

2023-04-05 01:37 UTC, kibaekkim requested changes
Please address the following:
- add comments for the new functions with inline comments in client_optimizer.py
- add comments for the arguments in mnist_no_mpi.py
- add a test for LBFGS
- update the document

2023-04-24 15:51 UTC, minseok-ryu commented
Q. What do you mean by adding a test for LBFGS?

2023-04-24 16:03 UTC, kibaekkim commented
> @kibaekkim Q. What do you mean by adding a test for LBFGS?

I was thinking something like this: https://github.com/APPFL/APPFL/blob/main/tests/test_mnist.py

2023-04-24 16:24 UTC, minseok-ryu commented
@kibaekkim Does it just test whether the code is run or not?

2023-04-24 19:38 UTC, kibaekkim requested changes
- Why were many lines in `test_mnist.py` commented out?
- To implement the training with closure in `training_closure`, create a class (e.g., `ClientOptimClosure`) that implements the training with closure in function `training`.

2023-04-24 20:24 UTC, kibaekkim commented on src/appfl/algorithm/client_optimizer.py
> +class ClientOptimClosure(ClientOptim):
move this class to a separate file

2023-04-24 21:13 UTC, kibaekkim commented on tests/test_mnist.py
> +    """
Create a separate function to test LBFGS.

2023-04-24 21:15 UTC, kibaekkim commented
@yim0331 Can you check whether `tests/test_mnist.py` is running? and make sure that `cfg.fed.args.optim = "LBFGS"` is being tested?

2023-04-26 00:57 UTC, kibaekkim reviewed
#120 #119 must be resolved first.

2023-05-24 02:43 UTC, minseok-ryu commented
Need to figure out why the pytest is not working...

2023-05-24 14:40 UTC, minseok-ryu commented
@yim0331 Pytest works fine now. The problem was the newly introduced function "LBFGS" in the Pytest. I did not have the data downloading issue you mentioned.

2023-05-24 14:57 UTC, yim0331 commented
> @yim0331 Pytest works fine now. The problem was the newly introduced function "LBFGS" in the Pytest. I did not have the data downloading issue you mentioned.

I see. Then, I will create a new branch based on this to avoid conflict.

2023-08-03 20:19 UTC, kibaekkim approved these changes

2023-10-10 04:23 UTC, Zilinghan commented
I will merge this branch into `zilinghan/refactor` branch first, and then for a merge together to the main branch

2025-01-15 22:05 UTC, closed without merging