Femnist example
APPFL/APPFL pull request #116
Opened 2023-04-19 17:07 UTC by yim0331

FEMINIST Example updates include the issues [#112](https://github.com/APPFL/APPFL/issues/112) and [#109](https://github.com/APPFL/APPFL/pull/109)

2023-04-19 17:51 UTC, kibaekkim commented on examples/models/resnet.py
> +    if num_channel == 1:
Is this the case for FEMNIST?

2023-04-19 17:51 UTC, kibaekkim commented on examples/models/resnet.py
> +        # model.append(resnetmodel)
If we don't use these lines later, please remove these.

2023-04-19 18:44 UTC, yim0331 commented on examples/models/resnet.py
> +        model = ResNet(block=BasicBlock, layers=[2, 2, 2, 2],num_classes=num_classes, grayscale=True)
This is the Resnet Model for FEMNIST

2023-04-27 16:34 UTC, kibaekkim requested changes
@yim0331 Please add the description for class (e.g., `ResNet18_Weights`) and functions and in-line comments to the files in `examples`. In particular, the examples should provide a good guidance to users for how to use the package.

The modification to the `algorithm` part needs @minseok-ryu 's review.

2023-04-27 16:34 UTC, kibaekkim commented on src/appfl/run_mpi.py
> +            req = comm.send(ls, 0, tag=cid)
I believe we can use non-blocking communication here. Please use `isend`.

2023-04-27 20:34 UTC, kibaekkim commented
@yim0331 The PR should be tested with the new `build` CI. Please merge `main` to this branch.

2023-04-27 23:17 UTC, minseok-ryu approved these changes
Minor modifications in Algorithm look good to me.

2023-04-28 20:54 UTC, kibaekkim approved these changes

2023-04-28 20:56 UTC, merged