Personalized FL update
APPFL/APPFL pull request #182
Opened 2024-04-03 18:00 UTC by shourya01

In this PR,

- Added `PersonalizedClientStepOptim` to make PFL compatible with step updates.
- Changed update norm calculation in `PersonalizedClientOptim` and `PersonalizedClientStepOptim` to ensure accurate clipping. This is required for adding DP to PFL.
- DP is now only added to shared layers when using PFL algorithms.
- Updated docs for PFL.

2024-04-03 18:32 UTC, kibaekkim requested changes

2024-04-03 18:32 UTC, kibaekkim commented on docs/users/user_implemented_pfl_algorithm.rst
@shourya01 Can you add the summary description of the personalization? We should also note that the DP applied to the personalization is more efficient than the typical approach, because the noise is not applied to the personalized layers.

2024-04-03 18:32 UTC, kibaekkim commented on src/appfl/algorithm/personalized_client_step_optimizer.py
> +                # -----
The clipping is performed after the model is updated. Is this intended?

2024-04-03 22:05 UTC, shourya01 commented
@kibaekkim In the above commit,
- Added more details in PFL doc and mentioned benefit of lower noise enjoyed by PFL.
- Made the update calculation functions more verbose and easier to follow.

2024-04-04 20:09 UTC, kibaekkim approved these changes

2024-04-21 04:26 UTC, merged