Federated DR functionality
APPFL/APPFL pull request #202
Opened 2024-09-24 19:58 UTC by kaveenh

2024-10-01 02:34 UTC, Zilinghan commented
Hi @kaveenh, thanks a lot on your great effort! This PR looks great to me overall, and I just left few minor points regrading the code structure and function/file naming points above.

For the examples, I saw you are creating a new folder `examples/dr_metrics`. However, most of the files within that folder is a bit duplicated compared with the `examples` folder, so I suggest the following way to restructure the dr metrics example in the following way
- Put all dr related metrics directly into the corresponding configuration folder, e.g., for `examples/resources/configs/mnist/server_fedavg.yaml`, just make it having the the following content with an additional flag parameter `generate_dr_report`.
    ```
    data_readiness_configs:
      generate_dr_report: True
      output_dirname: "./output"
      output_filename: "data_readiness_report"
    ```
- Also, as indicated in the above comments, the `dr_metrics`, which is a general client configuration that should be shared among all clients, putting it into server configuration file's `client_configs` simplifies the setting up.
- To run with dr metric, the runners (e.g., `run_mpi.py`, `run_server.py`, etc.) may have some changes, just put the changes into the corresponding runners within the `examples` folder.

2024-10-01 02:35 UTC, Zilinghan requested changes

2024-10-01 02:35 UTC, Zilinghan commented on examples/data_readiness/grpc/resources/configs/mnist/client_1.yaml
As `dr_metrics` is the same for all clients in most cases, it should be put into server configuration file under `client_configs`

2024-10-01 02:35 UTC, Zilinghan commented on examples/data_readiness/globus_compute/resources/config_gc/clients.yaml
Similarly, the `dr_metrics` should be in the server configuration file, as it is a general client configuration

2024-10-01 02:44 UTC, kaveenh commented
Hi Zilinghan,

Thank you for the valuable feedback. I will revise the proposed changes and resubmit.

Best regards
Kaveen
________________________________
From: Zilinghan Li ***@***.***>
Sent: Monday, September 30, 2024 10:35:31 PM
To: APPFL/APPFL ***@***.***>
Cc: Hiniduma, Kaveen ***@***.***>; Mention ***@***.***>
Subject: Re: [APPFL/APPFL] Federated DR functionality (PR #202)

@ Zilinghan requested changes on this pull request. On src/appfl/agent/dr_agent. py: For this Agent definition file, I think it would be better if we could move those dr metric computing functions into appfl. misc. data or appfl. misc. data_readiness,


@Zilinghan requested changes on this pull request.

________________________________

On src/appfl/agent/dr_agent.py<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*discussion_r1778949268__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE2QdbfHS$>:

For this Agent definition file, I think it would be better if we could move those dr metric computing functions into appfl.misc.data or appfl.misc.data_readiness, so that these useful functions can be called somewhere else

________________________________

On src/appfl/agent/dr_agent.py<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*discussion_r1778951086__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE2T_n7xt$>:

It is probably better to call it DRServerAgent and rename the file as dr_server_agent.py

________________________________

On src/appfl/agent/server.py<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*discussion_r1778952874__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE_BO4IgB$>:

As we have that dr_agent.py, I wonder what data_readiness_report function here does.

________________________________

On examples/data_readiness/grpc/resources/configs/mnist/client_1.yaml<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*discussion_r1782037150__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE_qu5rnU$>:

As dr_metrics is the same for all clients in most cases, it should be put into server configuration file under client_configs

________________________________

On examples/data_readiness/globus_compute/resources/config_gc/clients.yaml<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*discussion_r1782037656__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE9cBbvwL$>:

Similarly, the dr_metrics should be in the server configuration file, as it is a general client configuration

—
Reply to this email directly, view it on GitHub<https://urldefense.com/v3/__https://github.com/APPFL/APPFL/pull/202*pullrequestreview-2334289200__;Iw!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE78UlGX5$>, or unsubscribe<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/A5PARJ65ATFHMWQAQ5DCI2TZZIC7HAVCNFSM6AAAAABOZBHMAOVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDGMZUGI4DSMRQGA__;!!KGKeukY!zpsmb6vmoyyoQz7RjaPfrFU8a-YrB-3M32ZW3EhlyAEdSVykuTsu-6be8_V9-l2k2vuAmeW95oeAnMrntW7e5KNxHWIVE2I6Tyow$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-10-01 02:49 UTC, Zilinghan commented on src/appfl/agent/dr_agent.py
As this dr_agent is basically used by the client side to generate DR report, I recommend to put its functionalities within the `ClientAgent` directly

2024-10-01 02:52 UTC, Zilinghan commented
@kaveenh Could you please also help to revise this tutorial accordingly for your experience when adding your more advanced DR usecase: https://github.com/APPFL/APPFL/blob/main/docs/tutorials/examples_custom_action.rst (mine version is too simplified

2024-10-03 18:18 UTC, kaveenh commented
In the meantime, I will work on the documentation with the DR use cases.

2024-10-06 15:52 UTC, Zilinghan commented
Hi @kaveenh, I fixed some minor points for this PR in [this commit](https://github.com/APPFL/APPFL/pull/202/commits/4c8456796d58fe3fffbced0398f3b68ccaf44b2a), and now it is ready for merging once the documentation is uploaded. Please note the following key changes in my fix:

- As the documentation mentions that user runs all scripts within the `examples` folder, such as `python globus_compute/run.py`, instead of `python run.py`, I changed all `../resources/` to `./resources/` in the configuration files.
- I updated the `appfl.comm.grpc.grpc_server_communicator` and `appfl.comm.mpi.mpi_server_communicator` to make the DR action a synchronous action, i.e., return to clients once receiving requests from all clients - Please include this change into the documentation.

Again, thanks a lot for your great work!

2024-10-06 19:42 UTC, kaveenh commented
Hi @Zilinghan 

Thank you for the valuable feedback and the help in reviewing the PR. I will note the changes and include them in the documentation.

2024-10-08 18:24 UTC, kaveenh commented
Hi @Zilinghan,

The documentation is now updated [here](https://github.com/APPFL/APPFL/pull/202/commits/18422e43574a1984700f7765b4e018fcb9b2d246). Please let me know if you have any concerns or suggestions for changes.

Thank you

2024-10-08 19:15 UTC, Zilinghan commented
> Hi @Zilinghan,
> 
> The documentation is now updated [here](https://github.com/APPFL/APPFL/pull/202/commits/18422e43574a1984700f7765b4e018fcb9b2d246). Please let me know if you have any concerns or suggestions for changes.
> 
> Thank you

@kaveenh Thanks, the documentation looks perfect to me. I will go ahead to approve and merge this PR.

2024-10-08 19:15 UTC, Zilinghan approved these changes

2024-10-08 19:15 UTC, merged