Save PyTorch Model
APPFL/APPFL pull request #50
Opened 2022-02-09 21:13 UTC by minseok-ryu

2022-02-09 21:49 UTC, minseok-ryu commented
After training, the trained model is saved in ".pt" in the "results" directory.
Regarding the "checkpoint", we can do that, but need more discussion what to save and how to save.
(web: https://pytorch.org/tutorials/beginner/saving_loading_models.html)

2022-02-12 15:54 UTC, kibaekkim requested changes
Please update the documentation.

2022-02-22 20:11 UTC, kibaekkim requested changes
As this PR modifies the logging part in `utils.py`, it may be good to address #51 here.

2022-02-22 20:11 UTC, kibaekkim commented on src/appfl/config/config.py
> +    is_init_point: bool = True
The default value would better be `False`, and the values below be empty string.

2022-02-24 21:45 UTC, kibaekkim approved these changes

2022-02-24 21:48 UTC, merged